# Generated by Django 5.0.2 on 2024-02-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Decription', models.CharField(max_length=50)),
                ('Qty', models.IntegerField(default=0)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userlogin',
            },
        ),
        migrations.CreateModel(
            name='usersign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usersign',
            },
        ),
    ]
