# Generated by Django 5.0.2 on 2024-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Person_nos', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Message', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'BookingTable',
            },
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Chefs',
            },
        ),
        migrations.CreateModel(
            name='demoorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
            ],
            options={
                'db_table': 'demo',
            },
        ),
        migrations.CreateModel(
            name='Foodmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Foodmenu',
            },
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.ImageField(upload_to='')),
                ('Qty', models.IntegerField(default=0)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'OrderMenu',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Content', models.CharField(max_length=550)),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
