# Generated by Django 5.0.2 on 2024-04-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
