# Generated by Django 5.0.2 on 2024-04-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0005_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='Decription',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='Qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='Total_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
