# Generated by Django 5.0.2 on 2024-04-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0006_foodmenu_decription_foodmenu_price_foodmenu_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodmenu',
            old_name='Decription',
            new_name='Description',
        ),
    ]
