# Generated by Django 5.0.2 on 2024-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0007_rename_decription_foodmenu_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Content', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'myCarousel',
            },
        ),
    ]
