# Generated by Django 5.0.2 on 2024-05-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0009_foodcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcart',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='Qty',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='Total_Amount',
        ),
        migrations.AlterModelTable(
            name='foodcart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='foodmenu',
            table=None,
        ),
    ]
