# Generated by Django 5.0.2 on 2024-05-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0013_booking_table_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_table',
            name='Date_Time',
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='Time',
            field=models.TimeField(),
        ),
    ]
