# Generated by Django 5.0.2 on 2024-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0015_alter_booking_table_date_alter_booking_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='Time',
            field=models.TimeField(null=True),
        ),
    ]
