# Generated by Django 5.0.2 on 2024-05-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0017_foodmenu_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='user',
        ),
    ]
