# Generated by Django 5.0.2 on 2024-05-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0018_remove_foodcart_user_remove_foodmenu_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
