# Generated by Django 5.0.2 on 2024-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadizeApp', '0019_alter_foodcart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersign',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='usersign',
            name='Fullname',
        ),
        migrations.AddField(
            model_name='usersign',
            name='Phone_No',
            field=models.IntegerField(null=True),
        ),
    ]
